@extends('layouts.app', ['title' => 'New research · Kindred'])
@section('content')
<section class="page-intro"><div><span class="eyebrow">New research</span><h1>Research institutional funders</h1><p class="lede">Describe one concrete funding need. Kindred combines it with your saved organization profile to find up to four evidence-backed opportunities.</p></div><div class="intro-proof"><span>Public and licensed sources</span><span>Evidence required for every claim</span><span>Scores calculated from verified signals</span></div></section>
<div class="grid two section"><form class="panel panel-pad research-form" method="POST" action="{{ route('research.store') }}">@csrf
@if($organization)
<input type="hidden" name="organization_id" value="{{ $organization->id }}"><input type="hidden" name="organization_name" value="{{ $organization->name }}"><input type="hidden" name="website" value="{{ $organization->website }}"><input type="hidden" name="ein" value="{{ $organization->ein }}"><input type="hidden" name="nonprofit_status" value="{{ $organization->nonprofit_status }}"><input type="hidden" name="fiscal_sponsorship_status" value="{{ $organization->fiscal_sponsorship_status }}"><input type="hidden" name="mission" value="{{ $organization->mission }}"><input type="hidden" name="program_areas" value="{{ implode(', ',$organization->program_areas ?? []) }}"><input type="hidden" name="populations_served" value="{{ implode(', ',$organization->populations_served ?? []) }}"><input type="hidden" name="annual_budget" value="{{ $organization->annual_budget }}"><input type="hidden" name="staff_size" value="{{ $organization->staff_size }}"><input type="hidden" name="desired_grant_min" value="{{ $organization->desired_grant_min }}"><input type="hidden" name="desired_grant_max" value="{{ $organization->desired_grant_max }}"><input type="hidden" name="keywords" value="{{ implode(', ',$organization->keywords ?? []) }}"><input type="hidden" name="exclusions" value="{{ implode(', ',$organization->exclusions ?? []) }}">@if($organization->prefers_unrestricted)<input type="hidden" name="prefers_unrestricted" value="1">@endif
<div class="profile-summary"><span><span class="eyebrow">Researching for</span><strong>{{ $organization->name }}</strong><small>{{ $organization->website }} · {{ $organization->geography ?: 'Geography not set' }}</small></span><a href="{{ route('organization.edit') }}">Edit profile</a></div>
@else
<div class="notice"><strong>Set up your organization first</strong><br><span class="small">Your mission, geography, eligibility, programs, and funding preferences are required for useful results.</span><br><a href="{{ route('organization.edit') }}">Create organization profile →</a></div>
@endif
<div class="eyebrow section-label">Campaign</div><div class="field"><label for="campaign_title">What are you raising money for?</label><input id="campaign_title" name="campaign_title" required placeholder="Expand mobile food pantry deliveries in rural Vermont" value="{{ old('campaign_title') }}">@error('campaign_title')<div class="error">{{ $message }}</div>@enderror</div>
<div class="field"><label for="description">Campaign context</label><textarea id="description" name="description" required placeholder="Describe the program, who it serves, what funding pays for, and timing.">{{ old('description') }}</textarea>@error('description')<div class="error">{{ $message }}</div>@enderror</div>
<div class="grid form-two"><div class="field"><label for="goal_amount">Fundraising goal</label><div class="input-prefix"><span>$</span><input id="goal_amount" type="number" name="goal_amount" min="500" required placeholder="20,000" value="{{ old('goal_amount') }}"></div>@error('goal_amount')<div class="error">{{ $message }}</div>@enderror</div><div class="field"><label for="geography">Campaign geography</label><input id="geography" name="geography" value="{{ old('geography',$organization?->geography) }}" placeholder="Vermont"></div></div>
<div class="field"><label for="board_members">Board or relationship names <span class="muted">(optional)</span></label><textarea id="board_members" name="board_members" placeholder="Names separated by commas or lines">{{ old('board_members') }}</textarea></div>
<button class="button wide" @disabled(!$organization)>Begin research <span aria-hidden="true">→</span></button></form>
<aside><div class="panel panel-pad team-card"><div class="eyebrow">Inputs used in this run</div><h2>Organization context plus campaign need</h2><dl class="method-list"><div><dt>Organization</dt><dd>{{ $organization?->mission ?: 'Add a mission to improve relevance.' }}</dd></div><div><dt>Preferences</dt><dd>@if($organization) ${{ number_format($organization->desired_grant_min ?? 500) }}–${{ number_format($organization->desired_grant_max ?? 25000) }} · {{ implode(', ', $organization->desired_funding_categories ?? ['Any evidence-backed category']) }} @else Not configured @endif</dd></div><div><dt>Exclusions</dt><dd>{{ $organization && $organization->exclusions ? implode(', ',$organization->exclusions) : 'None configured' }}</dd></div><div><dt>Workflow</dt><dd>Strands agents research, verify, and synthesize. Laravel applies deterministic scoring and saves only validated results.</dd></div></dl></div>@if(!$demoMode)<div class="notice section"><b>Live research mode</b><br><span class="small">A failed external call remains visible and never substitutes unsupported data.</span></div>@endif</aside></div>
@if($runs->isNotEmpty())<section class="section"><div class="section-head"><h2>Recent research</h2><a class="small" href="{{ route('campaigns.index') }}">View all campaigns →</a></div><div class="panel panel-pad">@foreach($runs as $run)<a class="run-row" href="{{ route('research.show', $run) }}"><span><b>{{ $run->campaign->title }}</b><br><span class="muted small">{{ $run->campaign->organization->name }}</span></span><span>${{ number_format($run->campaign->goal_amount) }}</span><span class="status {{ $run->status->value === 'completed' ? 'complete' : '' }}">{{ str_replace('_', ' ', $run->status->value) }}</span></a>@endforeach</div></section>@endif
@endsection
