@extends('layouts.app', ['title' => $prospect->name.' · Kindred'])
@section('content')
@php($hasAsk=$prospect->grants->isNotEmpty() && $prospect->recommended_ask_min)
<a class="back" href="{{ route('research.show',$prospect->researchRun) }}">← Funding opportunities</a>
<div class="section-head"><div><span class="eyebrow">{{ $prospect->funder_type }} @if($prospect->ein)· EIN {{ $prospect->ein }}@endif</span><h1>{{ $prospect->name }}</h1><p class="lede">{{ $prospect->summary }}</p></div></div>

<section class="panel hero-score section"><div class="hero-stat"><span class="eyebrow">Path to money</span><strong>{{ strtoupper(str_replace('_',' ',$prospect->path_to_money_rating)) }}</strong><span class="muted small">{{ $prospect->path_completeness }}% of decision links resolved</span></div><div class="hero-stat"><span class="eyebrow">Deterministic fit</span><strong>{{ $prospect->eligibility_status==='ineligible' ? 'Ineligible' : $prospect->fit_score.'/100' }}</strong><span class="muted small">Hard eligibility overrides soft fit</span></div><div class="hero-stat"><span class="eyebrow">Recommended ask</span><strong>{{ $hasAsk ? '$'.number_format($prospect->recommended_ask_min).'–$'.number_format($prospect->recommended_ask_max) : 'Needs evidence' }}</strong><span class="muted small">Never a funding guarantee</span></div></section>

<section class="section"><div class="section-head"><div><span class="eyebrow">Causal decision path</span><h2>Could this organization actually receive the money?</h2></div></div><div class="panel path-list">@forelse($prospect->pathToMoneySteps as $step)<div class="path-step {{ $step->status }}"><span class="path-number">{{ $step->sequence }}</span><div><strong>{{ $step->label }}</strong><p>{{ $step->rationale }}</p>@if($step->claim)<details><summary class="evidence-link">Show evidence</summary><div class="evidence-drawer">@foreach($step->claim->evidence as $source)<div class="source"><div><b>Tier {{ $source->source_tier }} · {{ $source->title }}</b><div class="muted small">{{ $source->excerpt_or_locator }}</div></div><a href="{{ $source->url }}" target="_blank" rel="noopener noreferrer">Open source ↗</a></div>@endforeach</div></details>@endif</div><span class="path-status">{{ str_replace('_',' ',$step->status) }}</span></div>@empty<div class="empty panel-pad">This legacy prospect has not been evaluated yet.</div>@endforelse</div></section>

@if($prospect->researchTasks->isNotEmpty())<section class="panel panel-pad section"><span class="eyebrow">Unknown-resolution queue</span><h2 style="margin-top:7px">Research that could change the decision</h2><p class="muted">Prioritized by decision impact, uncertainty, resolvability, and cost.</p>@foreach($prospect->researchTasks as $task)<details class="research-task"><summary><span><strong>{{ $task->question }}</strong><small>{{ $task->why_it_matters }}</small></span><span class="information-value">Priority {{ number_format($task->information_value) }}</span></summary><div class="task-detail"><h3>Likely sources</h3><ul class="plain-list">@foreach($task->likely_sources as $source)<li>{{ $source }}</li>@endforeach</ul><h3>Targeted searches</h3><ul class="plain-list">@foreach($task->search_queries as $query)<li><code>{{ $query }}</code></li>@endforeach</ul><p><strong>Stop when:</strong> {{ implode('; ',$task->stop_conditions) }}.</p></div></details>@endforeach</section>@endif

<section class="section"><div class="section-head"><div><span class="eyebrow">Claim-level provenance</span><h2>Evidence supporting—and limiting—this recommendation</h2></div></div><div class="grid three">@foreach($prospect->claims as $claim)<article class="panel research-card"><span class="eyebrow">{{ str_replace('_',' ',$claim->predicate ?: $claim->key) }} · {{ str_replace('_',' ',$claim->status) }}</span><p><strong>{{ $claim->claim }}</strong></p><details><summary class="evidence-link">{{ $claim->evidence->count() }} {{ Str::plural('source',$claim->evidence->count()) }} →</summary><div class="evidence-drawer">@foreach($claim->evidence as $source)<div class="source"><div><b>Tier {{ $source->source_tier }} · {{ $source->title }}</b><div class="muted small">{{ $source->excerpt_or_locator }}<br>Retrieved {{ $source->retrieved_at->format('M j, Y') }}{{ $source->is_archived ? ' · Archived evidence' : '' }}</div></div><a href="{{ $source->url }}" target="_blank" rel="noopener noreferrer">Open source ↗</a></div>@endforeach</div></details></article>@endforeach</div></section>

<div class="grid two section"><section class="panel panel-pad"><span class="eyebrow">Historical award intelligence</span><h2>{{ $prospect->grants->count() }} sourced precedents</h2>@forelse($prospect->grants as $grant)<div class="grant-row"><b>{{ $grant->year }}</b><div><b>{{ $grant->recipient }}</b><div class="muted small">{{ $grant->purpose }}</div></div><b>${{ number_format($grant->amount) }}</b><a class="evidence-link" href="{{ $grant->source['url'] ?? '#' }}" target="_blank" rel="noopener noreferrer">Source ↗</a></div>@empty<div class="empty">No verified recipient or award-size precedent was found.</div>@endforelse</section><section class="panel panel-pad"><span class="eyebrow">Application feasibility</span><h2 style="margin-top:7px">{{ ucwords(str_replace('_',' ',$prospect->application_effort)) }} burden</h2><p>{{ $prospect->possible_disqualifiers ? 'Possible disqualifiers require review before applying.' : 'No explicit disqualifier was extracted, but unknowns may remain.' }}</p><ul class="decision-list">@foreach($prospect->possible_disqualifiers ?? [] as $item)<li>{{ $item }}</li>@endforeach</ul></section></div>

<div class="grid two section"><section class="panel panel-pad"><span class="eyebrow">Public contacts</span><h2 style="margin-top:7px">Who can resolve an unknown?</h2>@forelse($prospect->people as $person)<div class="person"><span class="avatar">{{ collect(explode(' ',$person->name))->map(fn($part)=>mb_substr($part,0,1))->take(2)->join('') }}</span><div><b>{{ $person->name }}</b><div class="muted small">{{ $person->role }}</div></div></div>@empty<div class="empty">No public professional contact was verified. Use the general grant inquiry channel on the official site.</div>@endforelse</section><section class="panel panel-pad"><span class="eyebrow">Recommended actions</span><h2 style="margin-top:7px">What to do next</h2><ol class="decision-list">@forelse($prospect->next_actions ?? [] as $action)<li>{{ $action }}</li>@empty<li>Resolve the highest-value unknown before beginning an application.</li>@endforelse</ol></section></div>

<section class="panel panel-pad section"><span class="eyebrow">Your decision</span><h2 style="margin-top:7px">Track this opportunity</h2><form method="POST" action="{{ route('prospects.feedback',$prospect) }}" class="chips" style="margin-top:18px">@csrf @foreach(['interested'=>'Interested','saved'=>'Save for later','not_relevant'=>'Not relevant','ineligible'=>'Ineligible','applied'=>'Applied','won'=>'Won','lost'=>'Lost'] as $value=>$label)<button class="button secondary" name="status" value="{{ $value }}">{{ $label }}</button>@endforeach</form><p style="margin-top:20px"><a class="button" href="{{ route('prospects.workspace',$prospect) }}">Open application workspace →</a></p></section>
@endsection
