@extends('layouts.app', ['title' => $run->campaign->title.' · Kindred'])
@section('content')
<a class="back" href="{{ route('research.index') }}">← New research</a>
<div class="section-head"><div><span class="eyebrow">{{ $run->status->value === 'completed' ? 'Funding landscape' : 'Researching your funding landscape' }}</span><h1>{{ $run->campaign->organization->name }}</h1><p class="lede">{{ $run->campaign->title }} · ${{ number_format($run->campaign->goal_amount) }} goal</p></div>@if($run->is_demo)<span class="mode demo">Demo data</span>@endif</div>

@if($run->status->value === 'failed')
<div class="panel panel-pad section"><span class="eyebrow" style="color:var(--danger)">Research interrupted</span><h2 style="margin-top:8px">We couldn't complete this run.</h2><p class="muted">{{ $run->failure_message }}</p><div class="notice">No unsupported funders were substituted. Refine the campaign context and start a new run.</div><p style="margin-top:20px"><a class="button" href="{{ route('research.index') }}">Start a new run →</a></p></div>
@elseif($run->status->value !== 'completed')
@php $stages=['campaign_analyst'=>'Understanding campaign fit and exclusions','evidence_researcher'=>'Verifying funders and grants','people_researcher'=>'Identifying public decision-makers and CRM paths','synthesizer'=>'Ranking evidence-backed opportunities']; $done=$run->events->where('status','completed')->pluck('node')->all(); @endphp
<div class="grid two section"><section class="panel panel-pad"><div class="eyebrow">Research pipeline</div><div style="margin-top:24px">@foreach($stages as $node=>$label)@php $complete=in_array($node,$done); $active=!$complete && collect(array_keys($stages))->search($node)===count($done); $event=$run->events->firstWhere('node',$node); @endphp<div class="stage {{ $complete ? 'complete' : ($active ? 'active' : '') }}"><span class="stage-dot">{{ $complete ? '✓' : '' }}</span><div><div class="stage-title">{{ $label }}</div><div class="stage-copy">{{ $event?->message ?? ($active ? 'Research in progress…' : 'Waiting for prior research') }}</div></div></div>@endforeach</div></section><aside class="grid"><section class="panel panel-pad"><div class="eyebrow">Research activity</div>@forelse($run->events->reverse() as $event)<div class="activity"><time>{{ $event->created_at->format('H:i') }}</time><div><b>{{ ucwords(str_replace('_',' ', $event->node)) }}</b><div class="muted small">{{ $event->message }}</div></div></div>@empty<p class="muted">Research is starting now. Keep this page open.</p>@endforelse</section></aside></div>
<script>(()=>{const token=document.querySelector('meta[name="csrf-token"]').content,endpoint=@json(route('research.execute',$run));let terminal=false,requestInFlight=false;async function poll(){if(terminal||requestInFlight)return;requestInFlight=true;try{const response=await fetch(endpoint,{method:'POST',headers:{'X-CSRF-TOKEN':token,'Accept':'application/json'},credentials:'same-origin'});const data=await response.json().catch(()=>({}));if(data.status==='completed'||data.status==='failed'||response.status===409){terminal=true;window.location.replace(window.location.href);return}}catch(_){}finally{requestInFlight=false}window.setTimeout(poll,document.hidden?5000:2000)}document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!terminal)poll()});poll()})();</script>
@else
@php $brief=$run->raw_agent_payload['campaign_brief'] ?? []; $excluded=$run->raw_agent_payload['excluded_candidates'] ?? []; $notes=$run->raw_agent_payload['research_notes'] ?? []; $fallbackCause=Str::contains(strtolower($run->campaign->title.' '.$run->campaign->description),['mental health','mental illness','psychiatric','clubhouse']) ? ['Mental health'] : ['Needs review']; $funderTypes=$brief['likely_funder_types'] ?? ['Private and community foundations','Corporate and hospital giving programs','Government grant programs']; $importantExclusions=$brief['important_exclusions'] ?? ['Wrong program area','Unsupported geography','Unverified eligibility','Untraceable evidence']; @endphp
<p class="lede">This landscape separates actionable opportunities from leads that still need verification.</p>
<section class="panel panel-pad section"><div class="section-head"><div><span class="eyebrow">What we understood</span><h2>Your campaign profile</h2></div><a class="evidence-link" href="{{ route('research.index') }}">Correct the inputs →</a></div><div class="brief-grid"><div><span class="muted small">Cause</span><b>{{ implode(', ', $brief['causes'] ?? $fallbackCause) }}</b></div><div><span class="muted small">Intervention</span><b>{{ $brief['intervention'] ?? $run->campaign->title }}</b></div><div><span class="muted small">Geography</span><b>{{ $brief['geography'] ?? ($run->campaign->organization->geography ?: 'Not specified') }}</b></div><div><span class="muted small">Funding goal</span><b>${{ number_format($run->campaign->goal_amount) }}</b></div></div><div class="grid two compact-grid"><div><h3>Likely funder types</h3><ul class="plain-list">@foreach($funderTypes as $type)<li>{{ $type }}</li>@endforeach</ul></div><div><h3>Important exclusions</h3><ul class="plain-list">@foreach($importantExclusions as $item)<li>{{ $item }}</li>@endforeach</ul></div></div></section>
<div class="grid four section"><div class="panel metric"><strong>{{ $metrics['ready'] }}</strong><span>Ready to pursue</span></div><div class="panel metric"><strong>{{ $metrics['investigate'] }}</strong><span>Worth investigating</span></div><div class="panel metric"><strong>{{ $metrics['historical'] }}</strong><span>Historical signals</span></div><div class="panel metric"><strong>{{ count($excluded) }}</strong><span>Excluded after review</span></div></div>
<section class="section"><div class="section-head"><div><h2>Decision-ready landscape</h2><span class="muted small">Every lead is labeled by what the evidence proves.</span></div></div><div class="panel">@forelse($run->prospects as $prospect)@php $hasAsk=$prospect->grants->isNotEmpty() && $prospect->recommended_ask_min; @endphp<a class="prospect-card" href="{{ route('prospects.show',$prospect) }}"><div class="score-number">{{ $prospect->fit_score }}<small>Fit score</small></div><div><span class="match">{{ ucfirst(str_replace('_',' ',$prospect->opportunity_status)) }}</span><div class="prospect-name">{{ $prospect->name }}</div><div class="chips"><span class="chip">{{ str_replace('_',' ',$prospect->opportunity_type) }}</span><span class="chip">{{ $prospect->grants->count() }} verified grants</span><span class="chip">Eligibility {{ str_replace('_',' ',$prospect->eligibility_status) }}</span></div></div><div class="ask"><span>Ask guidance</span><strong>@if($hasAsk)${{ number_format($prospect->recommended_ask_min/1000) }}K–${{ number_format($prospect->recommended_ask_max/1000) }}K @else Awaiting amount evidence @endif</strong></div><span class="arrow">→</span></a>@empty<div class="empty"><b>No candidate passed every evidence gate.</b><br>Review what was excluded and refine the campaign context.</div>@endforelse</div></section>
@if($excluded)<section class="panel panel-pad section"><span class="eyebrow">Excluded after review</span><h2 style="margin-top:7px">What we ruled out—and why</h2><p class="muted">These names were considered but were not added to your ranked pipeline.</p>@foreach($excluded as $item)<div class="exclusion-row"><div><b>{{ $item['name'] }}</b><div class="muted small">{{ $item['reason'] }}</div></div><span class="status">Excluded</span></div>@endforeach</section>@endif
@if($notes)<section class="panel panel-pad section"><span class="eyebrow">Research notes</span><ul class="plain-list">@foreach($notes as $note)<li>{{ $note }}</li>@endforeach</ul></section>@endif
<section class="panel panel-pad section"><div class="eyebrow">How we researched this</div>@foreach($run->events as $event)<div class="activity"><time>{{ $event->created_at->format('H:i') }}</time><div><b>{{ ucwords(str_replace('_',' ',$event->node)) }}</b><div class="muted small">{{ $event->message }}</div></div></div>@endforeach</section>
@endif
@endsection
